version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Update to bind to 0.0.0.0
    volumes:
      - ./venv:/app/venv
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
