# Generated by Django 4.2.4 on 2023-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='search_keywords',
            field=models.CharField(default='general', max_length=200),
        ),
    ]
