# Generated by Django 4.2.4 on 2023-11-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_search_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
