# Generated by Django 4.2.4 on 2023-11-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0002_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
