# Generated by Django 4.2.4 on 2023-11-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0006_userreview_roomrating_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image_url',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='hotel_management.room')),
            ],
        ),
    ]
