# Generated by Django 4.2.4 on 2023-11-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0007_alter_roomimage_image_url_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='hotel_management.room'),
        ),
    ]
